### ISSUE TITLE
Setup translations

### ISSUE THREAD

**Issue by rullzer** [nursoda/twofactor_email#18]

**Comment by NewRedsquare** [comment]
Why not opening transifex project, i'll be happy to contribute . I don't know if translation project can be merged into Nextcloud's transifex ?

**Comment by tpokorra** [comment]
Looking at https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html, I tried to work with the translationtool.
Unfortunately, it did not catch the L10n text="..." from the vue files.
I have reported an issue and files a pull request: https://github.com/nextcloud/docker-ci/issues/294

**Comment by nursoda** [comment]
Anyone willing to contribute is welcome. I have zero experience in L10n or setting up transifex.
