### ISSUE TITLE
show email domain

### ISSUE THREAD

**Issue by lvarnava** [nursoda/twofactor_email#193]
Hi, @rullzer !  Great respect for your work. Very necessary thing.

I am confused by the inscription: "An access code has been sent to *******a@mydomain.com"
Does such a hint make sense?
How safe is it?
And will it be possible in the future to customize the prompts yourself.
For a start, at least be able to hide it.

Sorry, if I was stupid.

**Comment by nursoda** [comment]
I agree that even displaying the masked email address may help an attacker. The question is whether it's helpful to display this information to valid users, or rather unnecessary. I tend to display the FULL address during setup/validation and to NOT display an address (but only the fact that a message has been sent to the email address that was set by the admin or user) for logins/authentication.

**Comment by nursoda** [comment]
Fixed on master.
