### ISSUE TITLE
Add a arrow on code enter window

### ISSUE THREAD

**Issue by TheRaven500** [nursoda/twofactor_email#317]
Hello
A simple enhancement:
Please add a -> arrow on the code enter window.
Of course you can enter the code and "hit" the enter-key.
But a button to click would be nice and takes the confusion how to login. :-)
Something like that for example (or a button on the bottom of the code enter window named "Login"):
![Button](https://user-images.githubusercontent.com/63654062/157726839-e83b9310-6531-434c-9ae9-04e637f978b7.jpg)!

Thanks a lot for this great app

**Comment by nursoda** [comment]
This has been resolved in #262, it's not released yet. I need some help with vue 2→3 and want to make sure the new version still works on NC24.

**Comment by TheRaven500** [comment]
Ah perfect, thank you very much! I'm new to this app so I didn't know it used to work. :-)
