### ISSUE TITLE
Nextcloud 25 Support

### ISSUE THREAD

**Issue by andyxheli** [nursoda/twofactor_email#351]

**Comment by nursoda** [comment]
There is [quite some work to do](https://github.com/nextcloud/server/issues/32117) prior to the release, like [switching to transifex](https://github.com/nursoda/twofactor_email/issues/350) and new theming. I did check for the [dev upgrade notes](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_25.html) but they only just got released and I didn't know about the first link in this post. So – anyone able to help getting it all done quickly?

**Comment by nursoda** [comment]
Done. Please leave a (positive) rating on https://apps.nextcloud.com/apps/twofactor_email

**Comment by andyxheli** [comment]
Looks good! Thank you!!
