### ISSUE TITLE
Allow remembered/trusted browser

### ISSUE THREAD

**Issue by dkebler** [nursoda/twofactor_email#372]
One of the downsides of this add on as is that every time you login you must get and supply a email 2FA code.

Even more problematic  (and I have not checked this out) but a nextcloud desktop client uses a browser to authenticate and thus every time it would have to go through this step (I assume like every time you reboot the machine).   

Further I wonder what happens with android/IOS apps?  

Anyway not being able to "trust" devices is an issue that pretty much makes this otherwise good add on a no go for me.  I can't see myself or my users being happy doing 2FA over and over on the the same machine same browser.

As I am sure many have seen it is possible to ask the user if they want to forgo further 2FA with that particular browser instance.   

Personally at this time I don't know how that is coded but this post indicates that it uses a browser cookie.
https://stackoverflow.com/questions/41228238/asp-net-identity-with-2fa-list-of-trusted-browsers 
https://apple.stackexchange.com/questions/352351/apples-2fa-and-the-notion-of-trusted-device-and-trusted-browser

So, I'd say this is another enhancement request and maybe you should add it to list.

**Comment by nursoda** [comment]
That is a misunderstanding. twofactor_email is just ONE of many 2FA "method" apps available ON TOP of a 2FA "framework" in Nextcloud. So this is the wrong place for what you ask. However, I'm going to answer shortly:

Nextcloud DOES NOT force you to authenticate EVERY TIME you use a Nextcloud app or the web interface. Authentication (no matter whether with or without 2FA) provides the app or browser with an access token. As long as you don't log out (or clear cookies of your Nextcloud domain in your browser), you stay logged in. That especially applies to apps on all mobile platforms.

There is room for improvement though: In contrast to other ecosystems (e.g. Amazon), Nextcloud does not provide a mechanism to save the 2nd factor state INDEPENDENTLY of the "logged in/out" status (yet). I assume that this is what you call "trust the device". I fully agree with you, that would be a great feature. Please start a discussion in the forum and/or search for open issues in nextcloud/server on GitHub.

Sidenote: The 2FA framework also does not allow to set a preferred (=used by default) 2FA mechanism if the user has multiple 2FA mechanisms configured. WordPress [Two-Factor](https://wordpress.org/plugins/two-factor/) does that nicely: It starts the default method right away and provides a link to a chooser if one wants to use another this time.

Note that all of the above has nothing to do with twofactor_* apps including twofactor_email, thus I'm closing this as invalid (for twofactor_email).
