### ISSUE TITLE
How to disable email provider for all users?

### ISSUE THREAD

**Issue by itverwaltung** [nursoda/twofactor_email#374]
Hi all,

we need to update out nextcloud instance from 25.0.13 to 26.0.10. After the update, all users having email 2fa provider can not login any more. The E-Mail is not sent.

I even disabled and deleted the app... After that, during login nextcloud is complaining about a missing 2fa provider.

![Missing_Provider](https://github.com/nursoda/twofactor_email/assets/47498433/bb44569b-28f7-45ac-a7bc-0efeeb2d1f96)

The translation is:

At least one of your 2fa providers could not be loaded. Contact your admin.

2fa is mandarory, but is not configured for your account. Use your Backup Codes or ask your admin for advice...

We dont have mandatory 2fa... 

Any hints?

Thank you very much...

Kind regards

Alex

**Comment by nursoda** [comment]
Hi Alex, this most probably is an issue with your [SMTP config](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html). There were changes in NC26 to the settings in config/config.php.

Another user reported after an [issue](https://github.com/nursoda/twofactor_email/issues/368) (in German via E-Mail): "Dein Tipp mit dem Mailserver war der Richtige. Warum auch immer die neue Version von NC nicht mittels der Serverumgebung mailen konnte weiß ich nicht. Über einen SMTP geht es aber jetzt wieder."

**Comment by itverwaltung** [comment]
Hi Olav,

yes, i didn’t see at the first, but you are right. After Updating to 26.0.10 the email function is broken…

We address this issue with nextcloud support. 

Thank you very much for your tipp...

kind regards

Alex
