### ISSUE TITLE
Explanation text and enable button are not displayed in IE11

### ISSUE THREAD

**Issue by devi69** [nursoda/twofactor_email#63]
### Steps to reproduce
1. Install and enable the "twofactor_email 1.0.1" APP.
2. Open Security of Personal Settings Page.
3. Confirm that the description is not displayed and that the enable button is not displayed.

### Expected behaviour
Even when displayed on IE11, the explanation and enable button are displayed.

### Actual behaviour
In IE11, explanation text and button are not displayed. It is displayed correctly in Google Chrome etc.

### Server configuration

**Operating system:** CentOS7

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** Nextcloud 17.0.1 

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Install from tarball package on nextcloud.com

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_email: 1.0.1
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external
  - twofactor_totp
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.16.204.65",
            "nc_17.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "https:\/\/nc_17.0.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

### Client configuration
**Browser:** Internet Explorer 11 (ver11.719.18362.0)

**Operating system:** Windows10

#### Browser log

![image](https://user-images.githubusercontent.com/23556623/77709222-badaab00-700d-11ea-8943-1f3bc78cf643.png)

**Comment by andyxheli** [comment]
IE 11 is end of life this year Microsoft dose not recomend using IE 11 as they suggest  use Edge 

https://redmondmag.com/articles/2020/08/17/end-of-support-ie11-and-edgehtml.aspx

@rullzer do you think this ticket should be closed?

**Comment by nursoda** [comment]
@devi69 I'm closing this issue as there's nothing we can do about it: Nextcloud uses vue.js to display everything and all the app does is to use the existing framework with content to be displayed as parameters. The issue you encountered would have needed to be fixed in vue.js I suppose.

If you are able to re-test your issue, please do so and report your mileage here but I won't put effort into this. In the IE that comes with recent W10, I could not even display the main login page of any Nextcloud server. So I urge you to use a modern browser as pointed out by @andyxheli .
